=== EricMacarroCanton/LMGSI/LMSGI_JSON/PART1_XML-JSON/Botiga.dtd
<!ELEMENT botiga (producte+)>
<!ATTLIST botiga
    nom CDATA #REQUIRED
    moneda CDATA #REQUIRED
>

<!ELEMENT producte (nom, descripcio, preu, categoria, disponibilitat, imatge)>
<!ATTLIST producte
    codi CDATA #REQUIRED
>

<!ELEMENT nom (#PCDATA)>
<!ELEMENT descripcio (#PCDATA)>
<!ELEMENT preu (#PCDATA)>
<!ELEMENT categoria (#PCDATA)>
<!ELEMENT disponibilitat (#PCDATA)>

<!ELEMENT imatge EMPTY>
<!ATTLIST imatge
    url CDATA #REQUIRED
>

=== EricMacarroCanton/LMGSI/LMSGI_JSON/PART1_XML-JSON/Botiga.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE botiga SYSTEM "botiga.dtd">

<!-- Document XML de la botiga online -->
<botiga nom="TechStore" moneda="EUR">

    <!-- Primer producte -->
    <producte codi="P001">
        <nom>Portàtil Lenovo IdeaPad</nom>
        <descripcio>Portàtil lleuger amb processador Intel i5 i 16GB de RAM</descripcio>
        <preu>799.99</preu>
        <categoria>Informàtica</categoria>
        <disponibilitat>En estoc</disponibilitat>
        <imatge url="https://www.exemple.com/imatges/lenovo.jpg"/>
    </producte>

    <!-- Segon producte -->
    <producte codi="P002">
        <nom>Auriculars Bluetooth Sony</nom>
        <descripcio>Auriculars sense fils amb cancel·lació de soroll</descripcio>
        <preu>149.99</preu>
        <categoria>Àudio</categoria>
        <disponibilitat>Esgotat</disponibilitat>
        <imatge url="https://www.exemple.com/imatges/sony.jpg"/>
    </producte>

</botiga>
